### ISSUE TITLE
yapscan as-service null pointer

### ISSUE THREAD

**Issue by mihdim777** [fkie-cad/yapscan#15]
Hello!

I have compiled yapscan using cross compile, on Linux and testing on a windows VM. When I try to use it as a service I get the following error. I can see the service installed in Services, but cannot be started manually.

What do you think can I do? 
Thank you!

```
.\yapscan.exe as-service
WARNING: This feature is experimental!
WARNING: You will not see any output of the executed service. Using --log-path is strongly advised.
Removing service in case it exists already...
[SC] DeleteService SUCCESS
Done removing.
Installing service...
[SC] CreateService SUCCESS
Done installing service.
Starting service with arguments...

SERVICE_NAME: yapscan
        TYPE               : 10  WIN32_OWN_PROCESS
        STATE              : 4  RUNNING
                                (STOPPABLE, NOT_PAUSABLE, IGNORES_SHUTDOWN)
        WIN32_EXIT_CODE    : 0  (0x0)
        SERVICE_EXIT_CODE  : 0  (0x0)
        CHECKPOINT         : 0x0
        WAIT_HINT          : 0x0
        PID                : 4868
        FLAGS              :
Done starting service, yapscan should now be running as a service with the following arguments
[--help]
panic: runtime error: invalid memory address or nil pointer dereference
[signal 0xc0000005 code=0x0 addr=0x181 pc=0x1076606]

goroutine 1 [running]:
github.com/urfave/cli/v2.(*App).Setup(0xc0000ee2d0)
        github.com/urfave/cli/v2@v2.3.0/app.go:132 +0x26
github.com/urfave/cli/v2.(*App).RunContext(0x0, {0x145e688, 0xc0000100c0}, {0xc000042040, 0x3, 0x4})
        github.com/urfave/cli/v2@v2.3.0/app.go:231 +0x85
github.com/urfave/cli/v2.(*App).Run(...)
        github.com/urfave/cli/v2@v2.3.0/app.go:224
main.runApp({0xc000042040, 0x3, 0x4})
        github.com/fkie-cad/yapscan/cmd/yapscan/main.go:16 +0x65
main.main()
        github.com/fkie-cad/yapscan/cmd/yapscan/main.go:37 +0x4c
```

**Comment by targodan** [comment]
Hi and sorry for the late answer,

I have taken a quick look and the reason for the crash is not immediately clear to me. That being said, the crash is only in the proxy command, which starts yapscan as a service. The actual service is running and doing its thing. If you execute a longer-term command such as `yapscan as-service scan -r <rules.yar> --full-report --report-dir C:\tmp --all-processes` you can observe the yapscan.exe running as user SYSTEM under the taks manager and you can see the resulting report (assuming `C:\tmp` exists).

On another note, as the output you posted says:

> WARNING: You will not see any output of the executed service. Using --log-path is strongly advised.

thus running `yapscan.exe as-service --help` has practically no use. What you probably want is to run `yapscan.exe --help` to see the available commands and flags and then prepend the `as-service` to run said command as service. For example: In order to run `yapscan scan [additional-args]` as a service, you can just use `yapscan as-service scan [additional-args]`.

And one final note, for scanning you don't need to run as a service. Running yapscan as administrator is sufficient to read the process memory of all processes, even services (at least based on my experiments so far, please let me know if you find something yapscan cannot scan without SYSTEM, i.e. service, privileges!).

I hope this helps, please let me know if you have further questions! :)

Best,
Targodan

PS: I will take a quick look to see if I can't get rid of the crash, but its not a priority right now, as the service works and its an experimental feature for now.

**Comment by targodan** [comment]
I found the (dumb) reason for the crash. It will be fixed in the next release. :)

Note that the service itself already worked correctly, even without the upcoming fix.

**Comment by targodan** [comment]
Heya and sorry for the monologue, but exciting news.

Not only is the bug fixed, but I also implemented outptu forwarding. With release 0.14.0 (currently building) you'll even be able to see the output of the service in your console as if yapscan was running normally. Have fun with this! :)
